name: Virus Scan Action
on:
  workflow_dispatch:
    inputs:
      get_virus:
        description: I Love Virus !
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

permissions:
  contents: read # actions/checkoutに必要

jobs:
  virusscan:
    runs-on: windows-2022
    timeout-minutes: 10
    steps:
      # ソースコードのチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # ウィルススキャン
      - name: VirusDownload
        if: inputs.get_virus == 'true'
        run: |
          curl -L -o hoge.txt https://secure.eicar.org/eicar.com
          cat hoge.txt

      # ウィルススキャン
      - name: Scan
        run: |
          # 定義ファイル更新
          echo "Signature Update"
          C:"/Program Files/Windows Defender/MpCmdRun.exe" -SignatureUpdate -MMPC

          # スキャン実行
          echo "Start Scan"
          C:"/Program Files/Windows Defender/MpCmdRun.exe" -Scan -ScanType 3 -File $env:GITHUB_WORKSPACE -DisableRemediation
